"""empty message

Revision ID: cc6def31be99
Revises: 523e6b76e2ff
Create Date: 2019-10-31 14:35:12.014640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6def31be99'
down_revision = '523e6b76e2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('address_1', sa.String(length=140), nullable=True))
    op.add_column('sale', sa.Column('address_2', sa.String(length=140), nullable=True))
    op.add_column('sale', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('sale', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('sale', sa.Column('zipcode', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_sale_address_1'), 'sale', ['address_1'], unique=False)
    op.create_index(op.f('ix_sale_address_2'), 'sale', ['address_2'], unique=False)
    op.create_index(op.f('ix_sale_end_date'), 'sale', ['end_date'], unique=False)
    op.create_index(op.f('ix_sale_start_date'), 'sale', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_start_date'), table_name='sale')
    op.drop_index(op.f('ix_sale_end_date'), table_name='sale')
    op.drop_index(op.f('ix_sale_address_2'), table_name='sale')
    op.drop_index(op.f('ix_sale_address_1'), table_name='sale')
    op.drop_column('sale', 'zipcode')
    op.drop_column('sale', 'start_date')
    op.drop_column('sale', 'end_date')
    op.drop_column('sale', 'address_2')
    op.drop_column('sale', 'address_1')
    # ### end Alembic commands ###
