"""empty message

Revision ID: eab3271bbaa6
Revises: cc6def31be99
Create Date: 2020-04-23 18:51:41.746671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab3271bbaa6'
down_revision = 'cc6def31be99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address_1', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('address_2', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'country')
    op.drop_column('user', 'address_2')
    op.drop_column('user', 'address_1')
    # ### end Alembic commands ###
